/**
 * Compliance & legal-boundary guardrail.
 *
 * Addresses the problem statement's requirement that the agent "respects
 * legal boundaries and submission rules — especially for confidential or
 * restricted portals." This module does two things:
 *
 *  1. Detects requests that ask the agent to act *on behalf of* the user on
 *     an external portal (auto-submit, auto-login, enter credentials, bypass
 *     CAPTCHA/verification, etc.) and blocks those — the agent can advise
 *     and draft, but never autonomously submits applications or touches
 *     credentials on a government/institutional portal.
 *
 *  2. Stamps any AI-generated proposal/eligibility output with a clear
 *     "human validation required" notice, since the problem statement
 *     explicitly calls out that tailored drafts must balance accuracy and
 *     creativity and "often requires human validation" before submission.
 */

export interface ComplianceCheckResult {
  allowed: boolean;
  reason?: string;
  userMessage?: string;
}

// Patterns that indicate the user (or an injected instruction) is asking the
// agent to take autonomous action on a restricted/confidential portal rather
// than just draft content or explain eligibility.
const RESTRICTED_ACTION_PATTERNS: RegExp[] = [
  /\b(auto[- ]?submit)\b/i,
  /\bsubmit\b.*\b(application|form|portal)\b.*\bfor me\b/i,
  /\b(log\s?in|sign in) (to|on) (my|the) (portal|account|dpiit|sisfs|birac)/i,
  /\b(enter|use|input) my (password|otp|aadhaar|pan|credentials|login)/i,
  /\bbypass\b.*\b(captcha|otp|verification|2fa|login)\b/i,
  /\b(fill (out )?and submit|complete and submit) (the )?(form|application) (for|on behalf of) me\b/i,
  /\bact as me\b.*\b(portal|government|submit)/i,
];

export function checkComplianceForUserMessage(message: string): ComplianceCheckResult {
  for (const pattern of RESTRICTED_ACTION_PATTERNS) {
    if (pattern.test(message)) {
      return {
        allowed: false,
        reason: 'restricted_portal_action',
        userMessage:
          "I can't log into, auto-fill, or submit forms on government or institutional portals on your behalf — that's outside what's safe and compliant for an AI agent to do, especially where credentials, OTPs, or identity documents are involved. " +
          "What I *can* do: explain the exact eligibility criteria, draft your application content, walk you through the submission steps, or summarize the portal's requirements so you can submit it yourself with confidence.",
      };
    }
  }
  return { allowed: true };
}

/**
 * Appends a standardized human-validation notice to AI-generated proposal or
 * eligibility content. Keeps the disclosure visually distinct (Markdown
 * blockquote) so it renders clearly in the existing chat/proposal UI.
 */
export function withHumanValidationNotice(content: string, language: string = 'english'): string {
  const lang = (language || 'english').toLowerCase();
  const notices: Record<string, string> = {
    hindi:
      '> ⚠️ **मानव सत्यापन आवश्यक:** यह सामग्री IBM Granite द्वारा AI-जनित है। जमा करने से पहले कृपया सटीकता, अनुपालन और तथ्यों की पुष्टि किसी सलाहकार या आधिकारिक दिशानिर्देशों से करें।',
    punjabi:
      '> ⚠️ **ਮਾਨਵੀ ਪੁਸ਼ਟੀ ਲੋੜੀਂਦੀ:** ਇਹ ਸਮੱਗਰੀ IBM Granite ਦੁਆਰਾ AI-ਤਿਆਰ ਹੈ। ਜਮ੍ਹਾਂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸ਼ੁੱਧਤਾ ਅਤੇ ਪਾਲਣਾ ਦੀ ਪੁਸ਼ਟੀ ਕਿਸੇ ਸਲਾਹਕਾਰ ਜਾਂ ਅਧਿਕਾਰਤ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼ਾਂ ਨਾਲ ਕਰੋ।',
    english:
      '> ⚠️ **Human validation required:** This content was AI-generated by IBM Granite. Please verify accuracy, compliance, and current scheme guidelines with an advisor or the official portal before submission.',
  };
  const notice = notices[lang] || notices.english;
  return `${content.trim()}\n\n---\n\n${notice}`;
}
